version: '3.8'

services:
  postgres:
    container_name: conselho-backend
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - '5434:5432'
    restart: unless-stopped